name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Deploy backend
      run: |
        cd backend
        ./mvnw clean package
        scp target/your-backend.jar user@your-server:/path/to/deploy

    - name: Deploy frontend
      run: |
        cd frontend
        mvn clean package
        scp target/your-frontend.war user@your-server:/path/to/deploy

    - name: Deploy mobile app
      run: |
        cd mobile
        ./gradlew assembleRelease
        scp app/build/outputs/apk/release/app-release.apk user@your-server:/path/to/deploy
