
name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: pharmacy

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build and test backend
      run: |
        cd backend
        ./mvnw clean install

    - name: Build and test frontend
      run: |
        cd frontend
        mvn clean install

    - name: Build and test mobile app
      run: |
        cd mobile
        ./gradlew build
